WITH CTE AS (

select


TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME,

CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat', 'Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,

CASE
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (12, 1, 2)  THEN 'Winter'
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (3, 4, 5)   THEN 'Spring'
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (6, 7, 8)   THEN 'Summer'
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (9, 10, 11) THEN 'Autumn'
    ELSE 'Unknown'

    End AS STATION_OF_YEAR


from
{{source('demo', 'bike')}}
where STARTED_AT != 'started_at'

)

select * from CTE
