WITH TRIPS as (

select

RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
START_STATIO_ID as START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL as MEMBER_CASUAL,
TIMESTAMPDIFF(seconD, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) as TRIP_DURATION



from {{source('demo', 'bike')}}

where RIDE_ID != 'ride_id'

limit 10
)

Select * from TRIPS